var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});

var workouts = [
  {
    type: 'General Training',
	setOne: '5 Sets of 5 Bench Press at ',
	setTwo: '4 sets of 8 Dumbbell Flys at ',
	setThree: '3 sets of 10 Barbell Curls at ',
	setFour: '3 sets of 15 Chin-Ups with ',
	
	secondOne: '3 sets of 10 Deadlift at ',
	secondTwo: '3 sets of 10 Barbell Rows at ',
	secondThree: '3 sets of 12 Hanging Leg Raises',
	secondFour: '3 sets of 20 V-Ups',
	
	thirdOne: '4 sets of 10 Overhead Press at ',
	thirdTwo: '2 sets of 12 Upright Rows at ',
	thirdThree: '4 sets of 8 Skull Crushers at ',
	thirdFour: '3 sets of 12 Dips',
	
	fourthOne: '3 sets of 10 Decline Barbell Bench Press at ',
	fourthTwo: '3 sets of 20 Push-ups',
	fourthThree: '4 sets of 8 Preacher Curls at ',
	fourthFour: '3 sets of 12 Reverse curls at ',
	
	fiveOne: '5 Sets of 5 Back Squat at ',
	fiveTwo: '5 sets of 15 each leg jumping lunges',
	fiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	fiveFour: '4 sets of 20 Standing Calf Raises',
	//week2
	twosetOne: '5 Sets of 5 Bench Press at ',
	twosetTwo: '4 sets of 8 Dumbbell Flys at ',
	twosetThree: '3 sets of 10 Barbell Curls at ',
	twosetFour: '3 sets of 15 Chin-Ups with ',
	
	twosecondOne: '3 sets of 10 Deadlift at ',
	twosecondTwo: '3 sets of 10 Barbell Rows at ',
	twosecondThree: '3 sets of 12 Hanging Leg Raises',
	twosecondFour: '3 sets of 20 V-Ups',
	
	twothirdOne: '4 sets of 10 Overhead Press at ',
	twothirdTwo: '2 sets of 12 Upright Rows at ',
	twothirdThree: '4 sets of 8 Skull Crushers at ',
	twothirdFour: '3 sets of 12 Dips',
	
	twofourthOne: '3 sets of 10 Decline Barbell Press at ',
	twofourthTwo: '3 sets of 20 Push-ups',
	twofourthThree: '4 sets of 8 Preacher Curls at ',
	twofourthFour: '3 sets of 12 Reverse curls at ',
	
	twofiveOne: '5 Sets of 5 Back Squat at ',
	twofiveTwo: '5 sets of 15 each leg jumping lunges',
	twofiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	twofiveFour: '4 sets of 20 Standing Calf Raises',
	//week3
	threesetOne: '5 Sets of 5 Bench Press at ',
	threesetTwo: '4 sets of 8 Dumbbell Flys at ',
	threesetThree: '3 sets of 10 Barbell Curls at ',
	threesetFour: '3 sets of 15 Chin-Ups with ',
	
	threesecondOne: '3 sets of 10 Deadlift at ',
	threesecondTwo: '3 sets of 10 Barbell Rows at ',
	threesecondThree: '3 sets of 12 Hanging Leg Raises',
	threesecondFour: '3 sets of 20 V-Ups',
	
	threethirdOne: '4 sets of 10 Overhead Press at ',
	threethirdTwo: '2 sets of 12 Upright Rows at ',
	threethirdThree: '4 sets of 8 Skull Crushers at ',
	threethirdFour: '3 sets of 12 Dips',
	
	threefourthOne: '3 sets of 10 Decline Barbell Press at ',
	threefourthTwo: '3 sets of 20 Push-ups',
	threefourthThree: '4 sets of 8 Preacher Curls at ',
	threefourthFour: '3 sets of 12 Reverse curls at ',
	
	threefiveOne: '5 Sets of 5 Back Squat at ',
	threefiveTwo: '5 sets of 15 each leg jumping lunges',
	threefiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	threefiveFour: '4 sets of 20 Standing Calf Raises',
	//week4
	foursetOne: '5 Sets of 5 Bench Press at ',
	foursetTwo: '4 sets of 8 Dumbbell Flys at ',
	foursetThree: '3 sets of 10 Barbell Curls at ',
	foursetFour: '3 sets of 15 Chin-Ups with ',
	
	foursecondOne: '3 sets of 10 Deadlift at ',
	foursecondTwo: '3 sets of 10 Barbell Rows at ',
	foursecondThree: '3 sets of 12 Hanging Leg Raises',
	foursecondFour: '3 sets of 20 V-Ups',
	
	fourthirdOne: '4 sets of 10 Overhead Press at ',
	fourthirdTwo: '2 sets of 12 Upright Rows at ',
	fourthirdThree: '4 sets of 8 Skull Crushers at ',
	fourthirdFour: '3 sets of 12 Dips',
	
	fourfourthOne: '3 sets of 10 Decline Barbell Press at ',
	fourfourthTwo: '3 sets of 20 Push-ups',
	fourfourthThree: '4 sets of 8 Preacher Curls at ',
	fourfourthFour: '3 sets of 12 Reverse curls at ',
	
	fourfiveOne: '5 Sets of 5 Back Squat at ',
	fourfiveTwo: '5 sets of 15 each leg jumping lunges',
	fourfiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	fourfiveFour: '4 sets of 20 Standing Calf Raises',
	//week5
	fivesetOne: '5 Sets of 5 Bench Press at ',
	fivesetTwo: '4 sets of 8 Dumbbell Flys at ',
	fivesetThree: '3 sets of 10 Barbell Curls at ',
	fivesetFour: '3 sets of 15 Chin-Ups with ',
	
	fivesecondOne: '3 sets of 10 Deadlift at ',
	fivesecondTwo: '3 sets of 10 Barbell Rows at ',
	fivesecondThree: '3 sets of 12 Hanging Leg Raises',
	fivesecondFour: '3 sets of 20 V-Ups',
	
	fivethirdOne: '4 sets of 10 Overhead Press at ',
	fivethirdTwo: '2 sets of 12 Upright Rows at ',
	fivethirdThree: '4 sets of 8 Skull Crushers at ',
	fivethirdFour: '3 sets of 12 Dips',
	
	fivefourthOne: '3 sets of 10 Decline Barbell Press at ',
	fivefourthTwo: '3 sets of 20 Push-ups',
	fivefourthThree: '4 sets of 8 Preacher Curls at ',
	fivefourthFour: '3 sets of 12 Reverse curls at ',
	
	fivefiveOne: '5 Sets of 5 Back Squat at ',
	fivefiveTwo: '5 sets of 15 each leg jumping lunges',
	fivefiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	fivefiveFour: '4 sets of 20 Standing Calf Raises',
	//week6
	sixsetOne: '5 Sets of 5 Bench Press at ',
	sixsetTwo: '4 sets of 8 Dumbbell Flys at ',
	sixsetThree: '3 sets of 10 Barbell Curls at ',
	sixsetFour: '3 sets of 15 Chin-Ups with ',
	
	sixsecondOne: '3 sets of 10 Deadlift at ',
	sixsecondTwo: '3 sets of 10 Barbell Rows at ',
	sixsecondThree: '3 sets of 12 Hanging Leg Raises',
	sixsecondFour: '3 sets of 20 V-Ups',
	
	sixthirdOne: '4 sets of 10 Overhead Press at ',
	sixthirdTwo: '2 sets of 12 Upright Rows at ',
	sixthirdThree: '4 sets of 8 Skull Crushers at ',
	sixthirdFour: '3 sets of 12 Dips',
	
	sixfourthOne: '3 sets of 10 Decline Barbell Press at ',
	sixfourthTwo: '3 sets of 20 Push-ups',
	sixfourthThree: '4 sets of 8 Preacher Curls at ',
	sixfourthFour: '3 sets of 12 Reverse curls at ',
	
	sixfiveOne: '5 Sets of 5 Back Squat at ',
	sixfiveTwo: '5 sets of 15 each leg jumping lunges',
	sixfiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	sixfiveFour: '4 sets of 20 Standing Calf Raises'

  },
  {
    type: 'Body Building',
		setOne: '5 Sets of 5 Bench Press at ',
	setTwo: '4 sets of 8 Dumbbell Flys at ',
	setThree: '3 sets of 10 Barbell Curls at ',
	setFour: '3 sets of 15 Chin-Ups with ',
	secondOne: '3 sets of 10 Deadlift at ',
	secondTwo: '3 sets of 10 Barbell Rows at ',
	secondThree: '3 sets of 12 Hanging Leg Raises',
	secondFour: '3 sets of 20 V-Ups',
	thirdOne: '4 sets of 10 Overhead Press at ',
	thirdTwo: '2 sets of 12 Upright Rows at ',
	thirdThree: '4 sets of 8 Skull Crushers at ',
	thirdFour: '3 sets of 12 Dips',
	fourthOne: '3 sets of 10 Decline Barbell Press at ',
	fourthTwo: '3 sets of 20 Push-ups',
	fourthThree: '4 sets of 8 Preacher Curls at ',
	fourthFour: '3 sets of 12 Reverse curls at ',
	fiveOne: '5 Sets of 5 Back Squat at ',
	fiveTwo: '5 sets of 15 each leg jumping lunges',
	fiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	fiveFour: '4 sets of 20 Standing Calf Raises',
	
	twosetOne: '5 Sets of 5 Bench Press at ',
	twosetTwo: '4 sets of 8 Dumbbell Flys at ',
	twosetThree: '3 sets of 10 Barbell Curls at ',
	twosetFour: '3 sets of 15 Chin-Ups with ',
	twosecondOne: '3 sets of 10 Deadlift at ',
	twosecondTwo: '3 sets of 10 Barbell Rows at ',
	twosecondThree: '3 sets of 12 Hanging Leg Raises',
	twosecondFour: '3 sets of 20 V-Ups',
	twothirdOne: '4 sets of 10 Overhead Press at ',
	twothirdTwo: '2 sets of 12 Upright Rows at ',
	twothirdThree: '4 sets of 8 Skull Crushers at ',
	twothirdFour: '3 sets of 12 Dips',
	twofourthOne: '3 sets of 10 Decline Barbell Press at ',
	twofourthTwo: '3 sets of 20 Push-ups',
	twofourthThree: '4 sets of 8 Preacher Curls at ',
	twofourthFour: '3 sets of 12 Reverse curls at ',
	twofiveOne: '5 Sets of 5 Back Squat at ',
	twofiveTwo: '5 sets of 15 each leg jumping lunges',
	twofiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	twofiveFour: '4 sets of 20 Standing Calf Raises',
	
	threesetOne: '5 Sets of 5 Bench Press at ',
	threesetTwo: '4 sets of 8 Dumbbell Flys at ',
	threesetThree: '3 sets of 10 Barbell Curls at ',
	threesetFour: '3 sets of 15 Chin-Ups with ',
	threesecondOne: '3 sets of 10 Deadlift at ',
	threesecondTwo: '3 sets of 10 Barbell Rows at ',
	threesecondThree: '3 sets of 12 Hanging Leg Raises',
	threesecondFour: '3 sets of 20 V-Ups',
	threethirdOne: '4 sets of 10 Overhead Press at ',
	threethirdTwo: '2 sets of 12 Upright Rows at ',
	threethirdThree: '4 sets of 8 Skull Crushers at ',
	threethirdFour: '3 sets of 12 Dips',
	threefourthOne: '3 sets of 10 Decline Barbell Press at ',
	threefourthTwo: '3 sets of 20 Push-ups',
	threefourthThree: '4 sets of 8 Preacher Curls at ',
	threefourthFour: '3 sets of 12 Reverse curls at ',
	threefiveOne: '5 Sets of 5 Back Squat at ',
	threefiveTwo: '5 sets of 15 each leg jumping lunges',
	threefiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	threefiveFour: '4 sets of 20 Standing Calf Raises',
	
	foursetOne: '5 Sets of 5 Bench Press at ',
	foursetTwo: '4 sets of 8 Dumbbell Flys at ',
	foursetThree: '3 sets of 10 Barbell Curls at ',
	foursetFour: '3 sets of 15 Chin-Ups with ',
	foursecondOne: '3 sets of 10 Deadlift at ',
	foursecondTwo: '3 sets of 10 Barbell Rows at ',
	foursecondThree: '3 sets of 12 Hanging Leg Raises',
	foursecondFour: '3 sets of 20 V-Ups',
	fourthirdOne: '4 sets of 10 Overhead Press at ',
	fourthirdTwo: '2 sets of 12 Upright Rows at ',
	fourthirdThree: '4 sets of 8 Skull Crushers at ',
	fourthirdFour: '3 sets of 12 Dips',
	fourfourthOne: '3 sets of 10 Decline Barbell Press at ',
	fourfourthTwo: '3 sets of 20 Push-ups',
	fourfourthThree: '4 sets of 8 Preacher Curls at ',
	fourfourthFour: '3 sets of 12 Reverse curls at ',
	fourfiveOne: '5 Sets of 5 Back Squat at ',
	fourfiveTwo: '5 sets of 15 each leg jumping lunges',
	fourfiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	fourfiveFour: '4 sets of 20 Standing Calf Raises',
	
	fivesetOne: '5 Sets of 5 Bench Press at ',
	fivesetTwo: '4 sets of 8 Dumbbell Flys at ',
	fivesetThree: '3 sets of 10 Barbell Curls at ',
	fivesetFour: '3 sets of 15 Chin-Ups with ',
	fivesecondOne: '3 sets of 10 Deadlift at ',
	fivesecondTwo: '3 sets of 10 Barbell Rows at ',
	fivesecondThree: '3 sets of 12 Hanging Leg Raises',
	fivesecondFour: '3 sets of 20 V-Ups',
	fivethirdOne: '4 sets of 10 Overhead Press at ',
	fivethirdTwo: '2 sets of 12 Upright Rows at ',
	fivethirdThree: '4 sets of 8 Skull Crushers at ',
	fivethirdFour: '3 sets of 12 Dips',
	fivefourthOne: '3 sets of 10 Decline Barbell Press at ',
	fivefourthTwo: '3 sets of 20 Push-ups',
	fivefourthThree: '4 sets of 8 Preacher Curls at ',
	fivefourthFour: '3 sets of 12 Reverse curls at ',
	fivefiveOne: '5 Sets of 5 Back Squat at ',
	fivefiveTwo: '5 sets of 15 each leg jumping lunges',
	fivefiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	fivefiveFour: '4 sets of 20 Standing Calf Raises',
	
	sixsetOne: '5 Sets of 5 Bench Press at ',
	sixsetTwo: '4 sets of 8 Dumbbell Flys at ',
	sixsetThree: '3 sets of 10 Barbell Curls at ',
	sixsetFour: '3 sets of 15 Chin-Ups with ',
	sixsecondOne: '3 sets of 10 Deadlift at ',
	sixsecondTwo: '3 sets of 10 Barbell Rows at ',
	sixsecondThree: '3 sets of 12 Hanging Leg Raises',
	sixsecondFour: '3 sets of 20 V-Ups',
	sixthirdOne: '4 sets of 10 Overhead Press at ',
	sixthirdTwo: '2 sets of 12 Upright Rows at ',
	sixthirdThree: '4 sets of 8 Skull Crushers at ',
	sixthirdFour: '3 sets of 12 Dips',
	sixfourthOne: '3 sets of 10 Decline Barbell Press at ',
	sixfourthTwo: '3 sets of 20 Push-ups',
	sixfourthThree: '4 sets of 8 Preacher Curls at ',
	sixfourthFour: '3 sets of 12 Reverse curls at ',
	sixfiveOne: '5 Sets of 5 Back Squat at ',
	sixfiveTwo: '5 sets of 15 each leg jumping lunges',
	sixfiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	sixfiveFour: '4 sets of 20 Standing Calf Raises'
  },
  {
    type: 'Power Lifting',
	setOne: '5 Sets of 5 Bench Press at ',
	setTwo: '4 sets of 8 Dumbbell Flys at ',
	setThree: '3 sets of 10 Barbell Curls at ',
	setFour: '3 sets of 15 Chin-Ups with ',
	secondOne: '3 sets of 10 Deadlift at ',
	secondTwo: '3 sets of 10 Barbell Rows at ',
	secondThree: '3 sets of 12 Hanging Leg Raises',
	secondFour: '3 sets of 20 V-Ups',
	thirdOne: '4 sets of 10 Overhead Press at ',
	thirdTwo: '2 sets of 12 Upright Rows at ',
	thirdThree: '4 sets of 8 Skull Crushers at ',
	thirdFour: '3 sets of 12 Dips',
	fourthOne: '3 sets of 10 Decline Barbell Press at ',
	fourthTwo: '3 sets of 20 Push-ups',
	fourthThree: '4 sets of 8 Preacher Curls at ',
	fourthFour: '3 sets of 12 Reverse curls at ',
	fiveOne: '5 Sets of 5 Back Squat at ',
	fiveTwo: '5 sets of 15 each leg jumping lunges',
	fiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	fiveFour: '4 sets of 20 Standing Calf Raises',
	
	twosetOne: '5 Sets of 5 Bench Press at ',
	twosetTwo: '4 sets of 8 Dumbbell Flys at ',
	twosetThree: '3 sets of 10 Barbell Curls at ',
	twosetFour: '3 sets of 15 Chin-Ups with ',
	twosecondOne: '3 sets of 10 Deadlift at ',
	twosecondTwo: '3 sets of 10 Barbell Rows at ',
	twosecondThree: '3 sets of 12 Hanging Leg Raises',
	twosecondFour: '3 sets of 20 V-Ups',
	twothirdOne: '4 sets of 10 Overhead Press at ',
	twothirdTwo: '2 sets of 12 Upright Rows at ',
	twothirdThree: '4 sets of 8 Skull Crushers at ',
	twothirdFour: '3 sets of 12 Dips',
	twofourthOne: '3 sets of 10 Decline Barbell Press at ',
	twofourthTwo: '3 sets of 20 Push-ups',
	twofourthThree: '4 sets of 8 Preacher Curls at ',
	twofourthFour: '3 sets of 12 Reverse curls at ',
	twofiveOne: '5 Sets of 5 Back Squat at ',
	twofiveTwo: '5 sets of 15 each leg jumping lunges',
	twofiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	twofiveFour: '4 sets of 20 Standing Calf Raises',
	
	threesetOne: '5 Sets of 5 Bench Press at ',
	threesetTwo: '4 sets of 8 Dumbbell Flys at ',
	threesetThree: '3 sets of 10 Barbell Curls at ',
	threesetFour: '3 sets of 15 Chin-Ups with ',
	threesecondOne: '3 sets of 10 Deadlift at ',
	threesecondTwo: '3 sets of 10 Barbell Rows at ',
	threesecondThree: '3 sets of 12 Hanging Leg Raises',
	threesecondFour: '3 sets of 20 V-Ups',
	threethirdOne: '4 sets of 10 Overhead Press at ',
	threethirdTwo: '2 sets of 12 Upright Rows at ',
	threethirdThree: '4 sets of 8 Skull Crushers at ',
	threethirdFour: '3 sets of 12 Dips',
	threefourthOne: '3 sets of 10 Decline Barbell Press at ',
	threefourthTwo: '3 sets of 20 Push-ups',
	threefourthThree: '4 sets of 8 Preacher Curls at ',
	threefourthFour: '3 sets of 12 Reverse curls at ',
	threefiveOne: '5 Sets of 5 Back Squat at ',
	threefiveTwo: '5 sets of 15 each leg jumping lunges',
	threefiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	threefiveFour: '4 sets of 20 Standing Calf Raises',
	
	foursetOne: '5 Sets of 5 Bench Press at ',
	foursetTwo: '4 sets of 8 Dumbbell Flys at ',
	foursetThree: '3 sets of 10 Barbell Curls at ',
	foursetFour: '3 sets of 15 Chin-Ups with ',
	foursecondOne: '3 sets of 10 Deadlift at ',
	foursecondTwo: '3 sets of 10 Barbell Rows at ',
	foursecondThree: '3 sets of 12 Hanging Leg Raises',
	foursecondFour: '3 sets of 20 V-Ups',
	fourthirdOne: '4 sets of 10 Overhead Press at ',
	fourthirdTwo: '2 sets of 12 Upright Rows at ',
	fourthirdThree: '4 sets of 8 Skull Crushers at ',
	fourthirdFour: '3 sets of 12 Dips',
	fourfourthOne: '3 sets of 10 Decline Barbell Press at ',
	fourfourthTwo: '3 sets of 20 Push-ups',
	fourfourthThree: '4 sets of 8 Preacher Curls at ',
	fourfourthFour: '3 sets of 12 Reverse curls at ',
	fourfiveOne: '5 Sets of 5 Back Squat at ',
	fourfiveTwo: '5 sets of 15 each leg jumping lunges',
	fourfiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	fourfiveFour: '4 sets of 20 Standing Calf Raises',
	
	fivesetOne: '5 Sets of 5 Bench Press at ',
	fivesetTwo: '4 sets of 8 Dumbbell Flys at ',
	fivesetThree: '3 sets of 10 Barbell Curls at ',
	fivesetFour: '3 sets of 15 Chin-Ups with ',
	fivesecondOne: '3 sets of 10 Deadlift at ',
	fivesecondTwo: '3 sets of 10 Barbell Rows at ',
	fivesecondThree: '3 sets of 12 Hanging Leg Raises',
	fivesecondFour: '3 sets of 20 V-Ups',
	fivethirdOne: '4 sets of 10 Overhead Press at ',
	fivethirdTwo: '2 sets of 12 Upright Rows at ',
	fivethirdThree: '4 sets of 8 Skull Crushers at ',
	fivethirdFour: '3 sets of 12 Dips',
	fivefourthOne: '3 sets of 10 Decline Barbell Press at ',
	fivefourthTwo: '3 sets of 20 Push-ups',
	fivefourthThree: '4 sets of 8 Preacher Curls at ',
	fivefourthFour: '3 sets of 12 Reverse curls at ',
	fivefiveOne: '5 Sets of 5 Back Squat at ',
	fivefiveTwo: '5 sets of 15 each leg jumping lunges',
	fivefiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	fivefiveFour: '4 sets of 20 Standing Calf Raises',
	
	sixsetOne: '5 Sets of 5 Bench Press at ',
	sixsetTwo: '4 sets of 8 Dumbbell Flys at ',
	sixsetThree: '3 sets of 10 Barbell Curls at ',
	sixsetFour: '3 sets of 15 Chin-Ups with ',
	sixsecondOne: '3 sets of 10 Deadlift at ',
	sixsecondTwo: '3 sets of 10 Barbell Rows at ',
	sixsecondThree: '3 sets of 12 Hanging Leg Raises',
	sixsecondFour: '3 sets of 20 V-Ups',
	sixthirdOne: '4 sets of 10 Overhead Press at ',
	sixthirdTwo: '2 sets of 12 Upright Rows at ',
	sixthirdThree: '4 sets of 8 Skull Crushers at ',
	sixthirdFour: '3 sets of 12 Dips',
	sixfourthOne: '3 sets of 10 Decline Barbell Press at ',
	sixfourthTwo: '3 sets of 20 Push-ups',
	sixfourthThree: '4 sets of 8 Preacher Curls at ',
	sixfourthFour: '3 sets of 12 Reverse curls at ',
	sixfiveOne: '5 Sets of 5 Back Squat at ',
	sixfiveTwo: '5 sets of 15 each leg jumping lunges',
	sixfiveThree: '3 sets of 10 Stiff Legged Romanian Deadlift',
	sixfiveFour: '4 sets of 20 Standing Calf Raises'
  }
];

router.get('/theWorkout', function(req,res) {
  console.log("In workouts");
  res.send(workouts);
});

module.exports = router;
